#!/usr/bin/env python3
"""gen_version_proxy: writes the version.dll forwarding layer from the system version.dll's export table.

  src/version.def        exports with the system DLL's names and ordinals, each bound to a stub
  src/version_stubs.asm  one stub per export: jmp through g_verReal[i] (x64 MASM)
  src/version_names.h    the export names in the same order, for GetProcAddress

The stubs jump, they do not call, so every argument, return value and error code is the real DLL's. Run it again
only if Windows ever adds an export to version.dll.
"""
import os
import struct

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "..", "src")
def read_exports(path):
    """(name, ordinal) of every named export, in name-table order."""
    d = open(path, "rb").read()
    u16 = lambda o: struct.unpack_from("<H", d, o)[0]
    u32 = lambda o: struct.unpack_from("<I", d, o)[0]
    pe = u32(0x3C)
    opt = pe + 24
    if u16(opt) != 0x20B:
        raise SystemExit("not a 64-bit DLL: " + path)
    sections = [struct.unpack_from("<IIII", d, opt + u16(pe + 20) + i * 40 + 8) for i in range(u16(pe + 6))]

    def off(rva):
        for vsize, va, rsize, raw in sections:
            if va <= rva < va + max(vsize, rsize):
                return rva - va + raw
        raise SystemExit("rva outside the sections: %x" % rva)

    exp = off(u32(opt + 112))
    base, count, names, ords = u32(exp + 16), u32(exp + 24), off(u32(exp + 32)), off(u32(exp + 36))
    out = []
    for i in range(count):
        n = off(u32(names + i * 4))
        out.append((d[n:d.index(b"\0", n)].decode(), base + u16(ords + i * 2)))
    return out


# a forwarded export still resolves through GetProcAddress on the real DLL, so the stubs cover it
exports = read_exports(os.path.join(os.environ["WINDIR"], "System32", "version.dll"))

with open(os.path.join(src, "version.def"), "w", newline="\r\n") as f:
    f.write("; generated by tools/gen_version_proxy.py from System32\\version.dll\nLIBRARY version\nEXPORTS\n")
    for name, ordinal in exports:
        f.write("    %s=stub_%s @%d\n" % (name, name, ordinal))

with open(os.path.join(src, "version_stubs.asm"), "w", newline="\r\n") as f:
    f.write("; generated by tools/gen_version_proxy.py: every version.dll export jumps to the real function\n")
    f.write("EXTERN g_verReal:QWORD\n.code\n")
    for i, (name, _) in enumerate(exports):
        f.write("stub_%s PROC\n    jmp qword ptr [g_verReal + %d]\nstub_%s ENDP\n" % (name, i * 8, name))
    f.write("END\n")

with open(os.path.join(src, "version_names.h"), "w", newline="\r\n") as f:
    f.write("// generated by tools/gen_version_proxy.py: version.dll export names in stub order\n#pragma once\n")
    f.write("static const char *const kVerNames[] = {\n")
    for name, _ in exports:
        f.write('    "%s",\n' % name)
    f.write("};\nstatic const int kVerCount = %d;\n" % len(exports))
print("%d exports written" % len(exports))
