; generated by tools/gen_version_proxy.py: every version.dll export jumps to the real function
EXTERN g_verReal:QWORD
.code
stub_GetFileVersionInfoA PROC
    jmp qword ptr [g_verReal + 0]
stub_GetFileVersionInfoA ENDP
stub_GetFileVersionInfoByHandle PROC
    jmp qword ptr [g_verReal + 8]
stub_GetFileVersionInfoByHandle ENDP
stub_GetFileVersionInfoExA PROC
    jmp qword ptr [g_verReal + 16]
stub_GetFileVersionInfoExA ENDP
stub_GetFileVersionInfoExW PROC
    jmp qword ptr [g_verReal + 24]
stub_GetFileVersionInfoExW ENDP
stub_GetFileVersionInfoSizeA PROC
    jmp qword ptr [g_verReal + 32]
stub_GetFileVersionInfoSizeA ENDP
stub_GetFileVersionInfoSizeExA PROC
    jmp qword ptr [g_verReal + 40]
stub_GetFileVersionInfoSizeExA ENDP
stub_GetFileVersionInfoSizeExW PROC
    jmp qword ptr [g_verReal + 48]
stub_GetFileVersionInfoSizeExW ENDP
stub_GetFileVersionInfoSizeW PROC
    jmp qword ptr [g_verReal + 56]
stub_GetFileVersionInfoSizeW ENDP
stub_GetFileVersionInfoW PROC
    jmp qword ptr [g_verReal + 64]
stub_GetFileVersionInfoW ENDP
stub_VerFindFileA PROC
    jmp qword ptr [g_verReal + 72]
stub_VerFindFileA ENDP
stub_VerFindFileW PROC
    jmp qword ptr [g_verReal + 80]
stub_VerFindFileW ENDP
stub_VerInstallFileA PROC
    jmp qword ptr [g_verReal + 88]
stub_VerInstallFileA ENDP
stub_VerInstallFileW PROC
    jmp qword ptr [g_verReal + 96]
stub_VerInstallFileW ENDP
stub_VerLanguageNameA PROC
    jmp qword ptr [g_verReal + 104]
stub_VerLanguageNameA ENDP
stub_VerLanguageNameW PROC
    jmp qword ptr [g_verReal + 112]
stub_VerLanguageNameW ENDP
stub_VerQueryValueA PROC
    jmp qword ptr [g_verReal + 120]
stub_VerQueryValueA ENDP
stub_VerQueryValueW PROC
    jmp qword ptr [g_verReal + 128]
stub_VerQueryValueW ENDP
END
